CREATE TABLE stock (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_ean VARCHAR2(255),
    quantity NUMBER,
    minQuantity NUMBER,
    lab_id NUMBER,
    FOREIGN KEY (item_ean) REFERENCES item(eanCode),
    FOREIGN KEY (lab_id) REFERENCES lab(id)
);
