CREATE TABLE operation_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    operationType VARCHAR2(255),
    item JSON,
    quantity NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
